name: 'Erotic Art - Drawings & Paintings by ErosArts'
favicon: null
layout_spectrum: 0.21226752712391317
typography_spectrum: 0.9734114450402558
title: 'Erotic Art - Drawings & Paintings by ErosArts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.06921274424530566
  lightness: 0.7375886994414032
  saturation: 0.8066827892325819
  rhythmicContrast: 0.5074442243203521
purpose: []
