name: 'Erotic Art - Drawings & Paintings by ErosArts'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9734114450402558
title: 'Erotic Art - Drawings & Paintings by ErosArts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0f1b'
    - '#753437'
    - '#5c6b94'
    - '#f7dfc7'
    - '#2a394c'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
